[tool.poetry]
name = "jumpstarter"
version = "0.1.0"
description = ""
authors = ["Miguel Angel Ajo Pelayo <majopela@redhat.com>",
           "Nick Cao <ncao@redhat.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.2"
click = "^8.1.7"
pyserial = "^3.5"

[tool.poetry.dependencies.jumpstarter-protocol]
git = "https://github.com/jumpstarter-dev/jumpstarter-protocol.git"
subdirectory = "python"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
