[project]
name = "jumpstarter-driver-tftp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Benny Zlotnik", email = "bzlotnik@redhat.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.6.2.post1",
    "jumpstarter",
    "jumpstarter-driver-opendal",
    "aiofiles>=24.1.0"
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=6.0.0",
    "pytest-anyio>=0.0.0",
    "pytest-asyncio>=0.0.0",
    "jumpstarter-testing"
]


[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../'}

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_tftp"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
