name: Trigger Packages Index Generation

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*'

env:
  TRIGGER: >
    ${{
      github.repository_owner == 'jumpstarter-dev' &&
      (github.ref == 'refs/heads/main' ||
       startsWith(github.ref, 'refs/tags/') ||
       startsWith(github.ref, 'refs/heads/release-'))
    }}

jobs:
  trigger-packages-index:
    runs-on: ubuntu-latest
    if: env.TRIGGER == 'true'
    steps:
      - name: Trigger packages repository index generation
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: jumpstarter-dev/packages
          event-type: generate-index
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "repository": "${{ github.repository }}"
            }
