apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
endpoint: grpc.jumpstarter.192.168.0.203.nip.io:8082
token: "<token>"
export:
  serial:
    type: "jumpstarter.drivers.pyserial.driver.PySerial"
    config:
      url: "/dev/ttyUSB0"
      baudrate: 1843200
  tftp:
    type: jumpstarter_driver_tftp.driver.TftpServer
    config:
      root_dir: "/var/lib/tftpboot/"
      host: "192.168.1.111"
      port: 6969
